[package]
name = "rust-os"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
lazy_static = { version = "1.0", features = ["spin_no_std"] }
multiboot2 = "0.15.1"
spin = "0.5.2"
volatile = "0.2.6"
