[package]
name = "vesa_framebuffer"
version = "0.1.0"
edition = "2021"

[dependencies]
# N.B. Make sure limine version matches kernel!
limine = "0.1.10"

[dependencies.bitvec]
version = "1"
default-features = false
features = ["atomic", "alloc"]
