[package]
name = "rust-os"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "1", features = ["spin_no_std"] }
limine = "0.1.10"
linked_list_allocator = "0.9"
pc-keyboard = "0.5"
pic8259 = "0.10"
spin = "0.5"
uart_16550 = "0.2"
volatile = "0.2"
x86_64 = "0.14"
