[package]
name = "fat"
version = "0.1.0"
edition = "2021"

[dependencies]
genio = { version = "0.2", default-features = false }
zerocopy = "0.6"

[[example]]
name = "fat-debug"

[dev-dependencies]
genio = { version = "0.2", default-features = true }
