[build]
target = "x86_64-rust_os.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-rust_os]
rustflags = ["-C", "link-arg=-Tlinker.ld"]
